apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jaeger-operator-service-cert
  namespace: observability
spec:
  secretName: jaeger-operator-service-cert
  dnsNames:
    - jaeger-operator-webhook-service.observability.svc
    - jaeger-operator-webhook-service.observability.svc.cluster.local
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: observability
spec:
  selfSigned: {}